//
//  LanguageKey.swift
//  EyeOnTask
//
//  Created by Mac on 28/05/19.
//  Copyright © 2019 Hemant. All rights reserved.
//

import Foundation

public class LanguageKey {
    
    static var header : String {return getValueFromLanguageJson(key: "header")!}
    static var sub_header : String {return getValueFromLanguageJson(key: "sub_header")!}
    static var user_name_hint : String {return getValueFromLanguageJson(key: "user_name_hint")!}
    static var inCorrect_user_name : String {return getValueFromLanguageJson(key: "inCorrect_user_name")!}
    static var next_btn : String {return getValueFromLanguageJson(key: "next_btn")!}
    static var pass_word : String {return getValueFromLanguageJson(key: "pass_word")!}
    static var login_btn : String {return getValueFromLanguageJson(key: "login_btn")!}
    static var rmbr_me : String {return getValueFromLanguageJson(key: "rmbr_me")!}
    static var use_another_account : String {return getValueFromLanguageJson(key: "use_another_account")!}
    static var frgt_pass_btn : String {return getValueFromLanguageJson(key: "frgt_pass_btn")!}
    static var forgot_screen_title : String {return getValueFromLanguageJson(key: "forgot_screen_title")!}
    static var pass_word_recvry : String {return getValueFromLanguageJson(key: "pass_word_recvry")!}
    static var pass_desc : String {return getValueFromLanguageJson(key: "pass_desc")!}
    static var back_btn_to_lgn : String {return getValueFromLanguageJson(key: "back_btn_to_lgn")!}
    static var alrdy_key : String {return getValueFromLanguageJson(key: "alrdy_key")!}
    static var reset_pass_btn : String {return getValueFromLanguageJson(key: "reset_pass_btn")!}
    static var pass_resey : String {return getValueFromLanguageJson(key: "key")!}
    static var key : String {return getValueFromLanguageJson(key: "pass_word")!}
    static var frgt_pass_match : String {return getValueFromLanguageJson(key: "frgt_pass_match")!}
    static var empty_client_list : String {return getValueFromLanguageJson(key: "empty_client_list")!}
    static var client_name : String {return getValueFromLanguageJson(key: "client_name")!}
    static var Account_type : String {return getValueFromLanguageJson(key: "account_type")!}
    static var client_email : String {return getValueFromLanguageJson(key: "client_email")!}
    static var mob_no : String {return getValueFromLanguageJson(key: "mob_no")!}
    static var gst_no : String {return getValueFromLanguageJson(key: "gst_no")!}
    static var tin_no : String {return getValueFromLanguageJson(key: "tin_no")!}
    static var industry : String {return getValueFromLanguageJson(key: "industry")!}
    static var state : String {return getValueFromLanguageJson(key: "state")!}
    static var save_btn : String {return getValueFromLanguageJson(key: "save_btn")!}
    static var industries : String {return getValueFromLanguageJson(key: "industries")!}
    static var accounting : String {return getValueFromLanguageJson(key: "accounting")!}
    static var advertising : String {return getValueFromLanguageJson(key: "advertising")!}
    static var biotechnology : String {return getValueFromLanguageJson(key: "biotechnology")!}
    static var communication : String {return getValueFromLanguageJson(key: "communication")!}
    static var consulting : String {return getValueFromLanguageJson(key: "consulting")!}
    static var email_empty : String {return getValueFromLanguageJson(key: "email_empty")!}
    static var email_error : String {return getValueFromLanguageJson(key: "email_error")!}
    static var c_e_mob : String {return getValueFromLanguageJson(key: "c_e_mob")!}
    static var country_error : String {return getValueFromLanguageJson(key: "country_error")!}
    static var state_error : String {return getValueFromLanguageJson(key: "state_error")!}
    static var status_radio_btn : String {return getValueFromLanguageJson(key: "status_radio_btn")!}
    static var active_radio_btn : String {return getValueFromLanguageJson(key: "active_radio_btn")!}
    static var inactive_radio_btn : String {return getValueFromLanguageJson(key: "inactive_radio_btn")!}
    static var fax : String {return getValueFromLanguageJson(key: "fax")!}
    static var skype : String {return getValueFromLanguageJson(key: "skype")!}
    static var twitter : String {return getValueFromLanguageJson(key: "twitter")!}
    static var cont_name : String {return getValueFromLanguageJson(key: "cont_name")!}
    static var site_name : String {return getValueFromLanguageJson(key: "site_name")!}
    static var site_default_checkBox : String {return getValueFromLanguageJson(key: "site_default_checkBox")!}
    static var err_site_name : String {return getValueFromLanguageJson(key: "err_site_name")!}
    static var jobs_screen_title : String {return getValueFromLanguageJson(key: "jobs_screen_title")!}
    static var pm : String {return getValueFromLanguageJson(key: "pm")!}
    static var am : String {return getValueFromLanguageJson(key: "am")!}
    static var sort_by_date : String {return getValueFromLanguageJson(key: "sort_by_date")!}
    static var sort_by_recent : String {return getValueFromLanguageJson(key: "sort_by_recent")!}
    static var search_job_code_client_name_address : String {return getValueFromLanguageJson(key: "search_job_code_client_name_address")!}
    static var format_problem : String {return getValueFromLanguageJson(key: "format_problem")!}
    static var job_no_available : String {return getValueFromLanguageJson(key: "job_no_available")!}
    static var err_no_jobs_found : String {return getValueFromLanguageJson(key: "err_no_jobs_found")!}
    static var jobs : String {return getValueFromLanguageJson(key: "jobs")!}
    static var clients : String {return getValueFromLanguageJson(key: "clients")!}
    static var logout : String {return getValueFromLanguageJson(key: "logout")!}
    static var err_check_network : String {return getValueFromLanguageJson(key: "err_check_network")!}
    static var filter_tasks_screen_title : String {return getValueFromLanguageJson(key: "filter_tasks_screen_title")!}
    static var job_status : String {return getValueFromLanguageJson(key: "job_status")!}
    static var reset : String {return getValueFromLanguageJson(key: "reset")!}
    static var filter : String {return getValueFromLanguageJson(key: "filter")!}
    static var err_filter_button : String {return getValueFromLanguageJson(key: "err_filter_button")!}
    static var sites_screen_title : String {return getValueFromLanguageJson(key: "sites_screen_title")!}
    static var search : String {return getValueFromLanguageJson(key: "search")!}
    static var add_site_screen_title : String {return getValueFromLanguageJson(key: "add_site_screen_title")!}
    static var address : String {return getValueFromLanguageJson(key: "address")!}
    static var default_contact : String {return getValueFromLanguageJson(key: "default_contact")!}
    static var submit_btn : String {return getValueFromLanguageJson(key: "submit_btn")!}
    static var site_add : String {return getValueFromLanguageJson(key: "site_add")!}
    static var edit_site_screen_title : String {return getValueFromLanguageJson(key: "edit_site_screen_title")!}
    static var update_btn : String {return getValueFromLanguageJson(key: "update_btn")!}
    static var site_update : String {return getValueFromLanguageJson(key: "site_update")!}
    static var title_add_job : String {return getValueFromLanguageJson(key: "title_add_job")!}
    static var Job_title : String {return getValueFromLanguageJson(key: "job_title")!}
    static var job_desc : String {return getValueFromLanguageJson(key: "job_desc")!}
    static var job_priority : String {return getValueFromLanguageJson(key: "job_priority")!}
    static var job_inst : String {return getValueFromLanguageJson(key: "job_inst")!}
    static var client_mand : String {return getValueFromLanguageJson(key: "client_mand")!}
    static var contact_name : String {return getValueFromLanguageJson(key: "contact_name")!}
    static var alt_mobile_number : String {return getValueFromLanguageJson(key: "alt_mobile_number")!}
    static var email : String {return getValueFromLanguageJson(key: "email")!}
    static var country : String {return getValueFromLanguageJson(key: "country")!}
    static var city : String {return getValueFromLanguageJson(key: "city")!}
    static var postal_code : String {return getValueFromLanguageJson(key: "postal_code")!}
    static var assign_to : String {return getValueFromLanguageJson(key: "assign_to")!}
    static var shdl_start : String {return getValueFromLanguageJson(key: "shdl_start")!}
    static var shdl_end : String {return getValueFromLanguageJson(key: "shdl_end")!}
    static var date_form : String {return getValueFromLanguageJson(key: "date_form")!}
    static var time_form : String {return getValueFromLanguageJson(key: "time_form")!}
    static var tag : String {return getValueFromLanguageJson(key: "tag")!}
    static var add : String {return getValueFromLanguageJson(key: "add")!}
    static var items_selected : String {return getValueFromLanguageJson(key: "items_selected")!}
    static var self_key : String {return getValueFromLanguageJson(key: "self_key")!}
    static var clear : String {return getValueFromLanguageJson(key: "clear")!}
    static var err_job_title : String {return getValueFromLanguageJson(key: "err_job_title")!}
    static var err_client_name : String {return getValueFromLanguageJson(key: "err_mob_lent")!}
    static var err_mob_lent : String {return getValueFromLanguageJson(key: "filter")!}
    static var err_alter_mob_lent : String {return getValueFromLanguageJson(key: "err_alter_mob_lent")!}
    static var err_addr : String {return getValueFromLanguageJson(key: "err_addr")!}
    static var err_empty_Title : String {return getValueFromLanguageJson(key: "err_empty_Title")!}
    static var err_start_end_date : String {return getValueFromLanguageJson(key: "err_start_end_date")!}
    static var err_due_start_date : String {return getValueFromLanguageJson(key: "err_due_start_date")!}
    static var err_start_end_time : String {return getValueFromLanguageJson(key: "err_start_end_time")!}
    static var err_due_start_time : String {return getValueFromLanguageJson(key: "err_due_start_time")!}
    static var title_detail : String {return getValueFromLanguageJson(key: "title_detail")!}
    static var not_available : String {return getValueFromLanguageJson(key: "not_available")!}
    static var location : String {return getValueFromLanguageJson(key: "location")!}
    static var map : String {return getValueFromLanguageJson(key: "map")!}
    static var view : String {return getValueFromLanguageJson(key: "view")!}
    static var no_desc : String {return getValueFromLanguageJson(key: "no_desc")!}
    static var instr : String {return getValueFromLanguageJson(key: "instr")!}
    static var no_instr : String {return getValueFromLanguageJson(key: "no_instr")!}
    static var fieldworkers : String {return getValueFromLanguageJson(key: "fieldworkers")!}
    static var no_fw_available : String {return getValueFromLanguageJson(key: "no_fw_available")!}
    static var tags : String {return getValueFromLanguageJson(key: "tags")!}
    static var no_tag : String {return getValueFromLanguageJson(key: "no_tag")!}
    static var status_dialog : String {return getValueFromLanguageJson(key: "status_dialog")!}
    static var job_status_change : String {return getValueFromLanguageJson(key: "job_status_change")!}
    static var dialog_alert : String {return getValueFromLanguageJson(key: "dialog_alert")!}
    static var job_det_email : String {return getValueFromLanguageJson(key: "job_det_email")!}
    static var desc_no : String {return getValueFromLanguageJson(key: "desc_no")!}
    static var no_inst : String {return getValueFromLanguageJson(key: "no_inst")!}
    static var no_avail : String {return getValueFromLanguageJson(key: "no_avail")!}
    static var ok : String {return getValueFromLanguageJson(key: "ok")!}
    static var no_contact_available : String {return getValueFromLanguageJson(key: "no_contact_available")!}
    static var low : String {return getValueFromLanguageJson(key: "low")!}
    static var medium : String {return getValueFromLanguageJson(key: "medium")!}
    static var high : String {return getValueFromLanguageJson(key: "high")!}
    static var no_Item_generate_inv : String {return getValueFromLanguageJson(key: "no_Item_generate_inv")!}
    static var Invoice_priview : String {return getValueFromLanguageJson(key: "Invoice_priview")!}
    static var dialog_error_title : String {return getValueFromLanguageJson(key: "dialog_error_title")!}
    static var title_chat : String {return getValueFromLanguageJson(key: "title_chat")!}
    static var title_invoice : String {return getValueFromLanguageJson(key: "title_invoice")!}
    static var title_payment : String {return getValueFromLanguageJson(key: "title_payment")!}
    static var items_screen_title : String {return getValueFromLanguageJson(key: "items_screen_title")!}
    static var list_item : String {return getValueFromLanguageJson(key: "list_item")!}
    static var qty : String {return getValueFromLanguageJson(key: "qty")!}
    static var addItem_screen_title : String {return getValueFromLanguageJson(key: "addItem_screen_title")!}
    static var item : String {return getValueFromLanguageJson(key: "item")!}
    static var fieldworker : String {return getValueFromLanguageJson(key: "fieldworker")!}
    static var items_name : String {return getValueFromLanguageJson(key: "items_name")!}
    static var part_no : String {return getValueFromLanguageJson(key: "part_no")!}
    static var hsn_code : String {return getValueFromLanguageJson(key: "hsn_code")!}
    static var description : String {return getValueFromLanguageJson(key: "description")!}
    static var quantity : String {return getValueFromLanguageJson(key: "quantity")!}
    static var rate : String {return getValueFromLanguageJson(key: "rate")!}
    static var unit : String {return getValueFromLanguageJson(key: "unit")!}
    static var discount : String {return getValueFromLanguageJson(key: "discount")!}
    static var tax : String {return getValueFromLanguageJson(key: "tax")!}
    static var tax_amount : String {return getValueFromLanguageJson(key: "tax_amount")!}
    static var total_amount : String {return getValueFromLanguageJson(key: "total_amount")!}
    static var Item_delete_button : String {return getValueFromLanguageJson(key: "Item_delete_button")!}
    static var added_successfully : String {return getValueFromLanguageJson(key: "added_successfully")!}
    static var updated_successfully : String {return getValueFromLanguageJson(key: "updated_successfully")!}
    static var item_remove : String {return getValueFromLanguageJson(key: "item_remove")!}
    static var deleted_successfully : String {return getValueFromLanguageJson(key: "deleted_successfully")!}
    static var no_invoice : String {return getValueFromLanguageJson(key: "no_invoice")!}
    static var invoice_date : String {return getValueFromLanguageJson(key: "invoice_date")!}
    static var due_date : String {return getValueFromLanguageJson(key: "due_date")!}
    static var print_invoice : String {return getValueFromLanguageJson(key: "print_invoice")!}
    static var email_invoice : String {return getValueFromLanguageJson(key: "email_invoice")!}
    static var subject : String {return getValueFromLanguageJson(key: "subject")!}
    static var message : String {return getValueFromLanguageJson(key: "message")!}
    static var discount_Error : String {return getValueFromLanguageJson(key: "discountError")!}
    static var please_add_item : String {return getValueFromLanguageJson(key: "please_add_item")!}
    static var please_enter_amount : String {return getValueFromLanguageJson(key: "please_enter_amount")!}
    static var please_enter_discount : String {return getValueFromLanguageJson(key: "please_enter_discount")!}
    static var please_enter_quality : String {return getValueFromLanguageJson(key: "please_enter_quality")!}
    static var please_add_fieldworker : String {return getValueFromLanguageJson(key: "please_add_fieldworker")!}
    static var contact_added_successfully : String {return getValueFromLanguageJson(key: "contact_added_successfully")!}
    static var contact_updated_successfully : String {return getValueFromLanguageJson(key: "contact_updated_successfully")!}
    static var chat_msg_hint : String {return getValueFromLanguageJson(key: "chat_msg_hint")!}
    static var camera : String {return getValueFromLanguageJson(key: "camera")!}
    static var gallery : String {return getValueFromLanguageJson(key: "gallery")!}
    static var today : String {return getValueFromLanguageJson(key: "today")!}
    static var open_file : String {return getValueFromLanguageJson(key: "open_file")!}
    static var user_nm : String {return getValueFromLanguageJson(key: "user_nm")!}
    static var time : String {return getValueFromLanguageJson(key: "time")!}
    static var title_feedback : String {return getValueFromLanguageJson(key: "title_feedback")!}
    static var feed_head : String {return getValueFromLanguageJson(key: "feed_head")!}
    static var feed_sub_head : String {return getValueFromLanguageJson(key: "feed_sub_head")!}
    static var sign : String {return getValueFromLanguageJson(key: "sign")!}
    static var title_history : String {return getValueFromLanguageJson(key: "title_history")!}
    static var title_documents : String {return getValueFromLanguageJson(key: "title_documents")!}
    static var total_inv_amt : String {return getValueFromLanguageJson(key: "total_inv_amt")!}
    static var paid_amt : String {return getValueFromLanguageJson(key: "paid_amt")!}
    static var due_amt : String {return getValueFromLanguageJson(key: "due_amt")!}
    static var pay_date : String {return getValueFromLanguageJson(key: "pay_date")!}
    static var lable_pay_type : String {return getValueFromLanguageJson(key: "lable_pay_type")!}
    static var amt : String {return getValueFromLanguageJson(key: "amt")!}
    static var notes : String {return getValueFromLanguageJson(key: "notes")!}
    static var cash : String {return getValueFromLanguageJson(key: "cash")!}
    static var cheque : String {return getValueFromLanguageJson(key: "cheque")!}
    static var credit_card : String {return getValueFromLanguageJson(key: "credit_card")!}
    static var debit_card : String {return getValueFromLanguageJson(key: "debit_card")!}
    static var direct_diposite : String {return getValueFromLanguageJson(key: "direct_diposite")!}
    static var title_cutomform : String {return getValueFromLanguageJson(key: "title_cutomform")!}
    static var switch_user : String {return getValueFromLanguageJson(key: "switch_user")!}
    static var new_version_msg : String {return getValueFromLanguageJson(key: "new_version_msg")!}
    static var eye_on_task_version : String {return getValueFromLanguageJson(key: "eye_on_task_version")!}
    static var item_detail : String {return getValueFromLanguageJson(key: "item_detail")!}
    static var fieldworker_detail : String {return getValueFromLanguageJson(key: "fieldworker_detail")!}
    static var fieldworkers_name : String {return getValueFromLanguageJson(key: "fieldworkers_name")!}
    static var confirmation : String {return getValueFromLanguageJson(key: "confirmation")!}
    static var cancel : String {return getValueFromLanguageJson(key: "cancel")!}
    static var remove : String {return getValueFromLanguageJson(key: "remove")!}
    static var done : String {return getValueFromLanguageJson(key: "done")!}
    static var settings : String {return getValueFromLanguageJson(key: "settings")!}
    static var location_is_disabled : String {return getValueFromLanguageJson(key: "location_is_disabled")!}
    static var location_main_setting : String {return getValueFromLanguageJson(key: "location_main_setting")!}
    static var location_app_setting : String {return getValueFromLanguageJson(key: "location_app_setting")!}
    static var login_error : String {return getValueFromLanguageJson(key: "login_error")!}
    static var warning : String {return getValueFromLanguageJson(key: "warning")!}
    static var new_version : String {return getValueFromLanguageJson(key: "new_version")!}
    static var update : String {return getValueFromLanguageJson(key: "update")!}
    static var project_sites_screen_title : String {return getValueFromLanguageJson(key: "project_sites_screen_title")!}
    static var contacts_screen_title : String {return getValueFromLanguageJson(key: "contacts_screen_title")!}
    static var add_contacts_screen_title : String {return getValueFromLanguageJson(key: "add_contacts_screen_title")!}
    static var photo_denied : String {return getValueFromLanguageJson(key: "photo_denied")!}
    static var success : String {return getValueFromLanguageJson(key: "success")!}
    static var reject : String {return getValueFromLanguageJson(key: "reject")!}
    static var job_start : String {return getValueFromLanguageJson(key: "job_start")!}
    static var network_issue : String {return getValueFromLanguageJson(key: "network_issue")!}
    static var submitted : String {return getValueFromLanguageJson(key: "submitted")!}
    static var user_name_pass : String {return getValueFromLanguageJson(key: "user_name_pass")!}
    static var user_name : String {return getValueFromLanguageJson(key: "user_name")!}
    static var user_pass : String {return getValueFromLanguageJson(key: "user_pass")!}
    static var enter_key : String {return getValueFromLanguageJson(key: "enter_key")!}
    static var select_valid_field_worker_name_list : String {return getValueFromLanguageJson(key: "select_valid_field_worker_name_list")!}
    static var enter_some_text_without_space : String {return getValueFromLanguageJson(key: "enter_some_text_without_space")!}
    static var start_date_must_greater_then_schedule_end_date : String {return getValueFromLanguageJson(key: "start_date_must_greater_then_schedule_end_date")!}
    static var start_date_must_less_then_schedule_end_date : String {return getValueFromLanguageJson(key: "start_date_must_less_then_schedule_end_date")!}
    static var select_schedule_start_date : String {return getValueFromLanguageJson(key: "select_schedule_start_date")!}
    static var select_schedule_end_date : String {return getValueFromLanguageJson(key: "select_schedule_end_date")!}
    static var add_atleast_one_field_worker : String {return getValueFromLanguageJson(key: "add_atleast_one_field_worker")!}
    static var add_client_name : String {return getValueFromLanguageJson(key: "add_client_name")!}
    static var select_job_priority_from_list : String {return getValueFromLanguageJson(key: "select_job_priority_from_list")!}
    static var enter_job_title : String {return getValueFromLanguageJson(key: "enter_job_title")!}
    static var no_job_title_available : String {return getValueFromLanguageJson(key: "no_job_title_available")!}
    static var no_tag_available : String {return getValueFromLanguageJson(key: "no_tag_available")!}
    static var do_you_want_reject_this_job : String {return getValueFromLanguageJson(key: "do_you_want_reject_this_job")!}
    static var do_you_want_can_this_job : String {return getValueFromLanguageJson(key: "do_you_want_can_this_job")!}
    static var location_not_available : String {return getValueFromLanguageJson(key: "location_not_available")!}
    static var install_the_twitter_app : String {return getValueFromLanguageJson(key: "install_the_twitter_app")!}
    static var install_the_skype_app : String {return getValueFromLanguageJson(key: "install_the_skype_app")!}
    static var do_you_want_change_name_image: String {return getValueFromLanguageJson(key: "do_you_want_change_name_image")!}
    static var fill_all_mandatory_questions : String {return getValueFromLanguageJson(key: "fill_all_mandatory_questions")!}
    static var enter_city : String {return getValueFromLanguageJson(key: "enter_city")!}
    static var enter_alternate_mobile_number : String {return getValueFromLanguageJson(key: "enter_alternate_mobile_number")!}
    static var enter_valid_alternate_mobile_number : String {return getValueFromLanguageJson(key: "enter_valid_alternate_mobile_number")!}
    static var enter_valid_mobile_number : String {return getValueFromLanguageJson(key: "enter_valid_mobile_number")!}
    static var tax_not_more_than : String {return getValueFromLanguageJson(key: "tax_not_more_than_100")!}
    static var select_payment_type : String {return getValueFromLanguageJson(key: "select_payment_type")!}
    static var enter_subject : String {return getValueFromLanguageJson(key: "enter_subject")!}
    static var enter_valid_receipt_email_id : String {return getValueFromLanguageJson(key: "enter_valid_receipt_email_id")!}
    static var breake : String {return getValueFromLanguageJson(key: "break")!}
    static var input_text_email : String {return getValueFromLanguageJson(key: "input_text_email")!}
    static var enter_receipt_email_id : String {return getValueFromLanguageJson(key: "enter_receipt_email_id")!}
    static var date_time_formate : String {return getValueFromLanguageJson(key: "date_time_formate")!}
    static var limit_mid : String {return getValueFromLanguageJson(key: "limit_mid")!}
    static var limit_high : String {return getValueFromLanguageJson(key: "limit_high")!}
    static var session_expire : String {return getValueFromLanguageJson(key: "session_expire")!}
    static var new : String {return getValueFromLanguageJson(key: "new")!}
    static var accepted : String {return getValueFromLanguageJson(key: "accepted")!}
    static var travelling : String {return getValueFromLanguageJson(key: "travelling")!}
    static var break_key : String {return getValueFromLanguageJson(key: "break_key")!}
    static var In_progress : String {return getValueFromLanguageJson(key: "In_progress")!}
    static var on_hold : String {return getValueFromLanguageJson(key: "on_hold")!}
    static var completed : String {return getValueFromLanguageJson(key: "completed")!}
    static var closed : String {return getValueFromLanguageJson(key: "closed")!}
    static var edit : String {return getValueFromLanguageJson(key: "edit")!}
    static var job_code : String {return getValueFromLanguageJson(key: "job_code")!}
    static var status_tr_fin_st : String {return getValueFromLanguageJson(key: "status_tr_fin_st")!}
    static var no : String {return getValueFromLanguageJson(key: "no")!}
    static var yes : String {return getValueFromLanguageJson(key: "yes")!}
    static var fill_mandtry : String {return getValueFromLanguageJson(key: "fill_mandtry")!}
    static var job_not_fount : String {return getValueFromLanguageJson(key: "job_not_fount")!}
    static var sync_alert : String {return getValueFromLanguageJson(key: "sync_alert")!}
    static var clear_data : String {return getValueFromLanguageJson(key: "clear_data")!}
    static var payment_recv : String {return getValueFromLanguageJson(key: "payment_recv")!}
    static var password : String {return getValueFromLanguageJson(key: "password")!}
    static var overview : String {return getValueFromLanguageJson(key: "overview")!}
    static var add_client : String {return getValueFromLanguageJson(key: "add_client")!}
    static var edit_client : String {return getValueFromLanguageJson(key: "edit_client")!}
    static var edit_contact : String {return getValueFromLanguageJson(key: "edit_contact")!}
    static var get_signature : String {return getValueFromLanguageJson(key: "get_signature")!}
    static var more : String {return getValueFromLanguageJson(key: "more")!}
    static var documet_appear : String {return getValueFromLanguageJson(key: "documet_appear")!}
    static var upload_file : String {return getValueFromLanguageJson(key: "upload_file")!}
    static var save_for_future_use : String {return getValueFromLanguageJson(key: "save_for_future_use")!}
    static var add_your_ans : String {return getValueFromLanguageJson(key: "add_your_ans")!}
    static var add_new_item : String {return getValueFromLanguageJson(key: "add_new_item")!}
    static var edit_item_details : String {return getValueFromLanguageJson(key: "edit_item_details")!}
    static var item_fw : String {return getValueFromLanguageJson(key: "item_fw")!}
    static var item_desc : String {return getValueFromLanguageJson(key: "item_desc")!}
    static var qty_hr : String {return getValueFromLanguageJson(key: "qty_hr")!}
    static var pay_full_payment : String {return getValueFromLanguageJson(key: "pay_full_payment")!}
    static var pay_partial_amount : String {return getValueFromLanguageJson(key: "pay_partial_amount")!}
    static var pay_now : String {return getValueFromLanguageJson(key: "pay_now")!}
    static var card_no : String {return getValueFromLanguageJson(key: "card_no")!}
    static var expr_date : String {return getValueFromLanguageJson(key: "expr_date")!}
    static var cvv : String {return getValueFromLanguageJson(key: "cvv")!}
    static var cr_debt_card : String {return getValueFromLanguageJson(key: "cr_debt_card")!}
    static var net_banking : String {return getValueFromLanguageJson(key: "net_banking")!}
    static var card_holder_nm : String {return getValueFromLanguageJson(key: "card_holder_nm")!}
    static var pay : String {return getValueFromLanguageJson(key: "pay")!}
    static var item_not_found : String {return getValueFromLanguageJson(key: "item_not_found")!}
    static var user_logout_msg : String {return getValueFromLanguageJson(key: "user_logout_msg")!}
    static var hint_empty : String {return getValueFromLanguageJson(key: "hint_empty")!}
    static var custom_form_list : String {return getValueFromLanguageJson(key: "custom_form_list")!}
    static var client_syn : String {return getValueFromLanguageJson(key: "client_syn")!}
    static var fr_pass_headr : String {return getValueFromLanguageJson(key: "fr_pass_headr")!}
    static var fr_dont_key : String {return getValueFromLanguageJson(key: "fr_dont_key")!}
    static var fr_set_key : String {return getValueFromLanguageJson(key: "fr_set_key")!}
    static var new_password : String {return getValueFromLanguageJson(key: "new_password")!}
    static var no_filter : String {return getValueFromLanguageJson(key: "no_filter")!}
    static var empty_tag : String {return getValueFromLanguageJson(key: "empty_tag")!}
    static var enter_ans : String {return getValueFromLanguageJson(key: "enter_ans")!}
    static var update_item : String {return getValueFromLanguageJson(key: "update_item")!}
    static var item_empty : String {return getValueFromLanguageJson(key: "item_empty")!}
    static var remove_item_msg : String {return getValueFromLanguageJson(key: "remove_item_msg")!}
    static var invoice_remove : String {return getValueFromLanguageJson(key: "invoice_remove")!}
    static var update_app_message : String {return getValueFromLanguageJson(key: "update_app_message")!}
    static var offline_feature_alert : String {return getValueFromLanguageJson(key: "offline_feature_alert")!}
    static var payment_ntwrk : String {return getValueFromLanguageJson(key: "payment_ntwrk")!}
    static var payment_type : String {return getValueFromLanguageJson(key: "payment_type")!}
    static var amount_required : String {return getValueFromLanguageJson(key: "amount_required")!}
    static var invoice_details : String {return getValueFromLanguageJson(key: "invoice_details")!}
    static var add_edit_item : String {return getValueFromLanguageJson(key: "add_edit_item")!}
    static var fw_valid : String {return getValueFromLanguageJson(key: "fw_valid")!}
    static var job_resume : String {return getValueFromLanguageJson(key: "job_resume")!}
    static var job_finish : String {return getValueFromLanguageJson(key: "job_finish")!}
    static var resume : String {return getValueFromLanguageJson(key: "resume")!}
    static var travel_start : String {return getValueFromLanguageJson(key: "travel_start")!}
    static var accept : String {return getValueFromLanguageJson(key: "Accept")!} 
    static var something_wrong : String {return getValueFromLanguageJson(key: "something_wrong")!}
    static var unable_to_connect : String {return getValueFromLanguageJson(key: "unable_to_connect")!}
    static var Sche_end_start_time : String {return getValueFromLanguageJson(key: "Sche_end_start_time")!}
    static var client_added : String {return getValueFromLanguageJson(key: "client_added")!}
    static var no_chat : String {return getValueFromLanguageJson(key: "no_chat")!}
    static var no_location : String {return getValueFromLanguageJson(key: "no_location")!}
    static var user_logout : String {return getValueFromLanguageJson(key: "user_logout")!}
    static var cnf_pass : String {return getValueFromLanguageJson(key: "cnf_pass")!}
    static var update_invoice : String {return getValueFromLanguageJson(key: "update_invoice")!}
    static var item_name : String {return getValueFromLanguageJson(key: "item_name")!}
    static var add_contact : String {return getValueFromLanguageJson(key: "add_contact")!}
    static var job_details: String {return getValueFromLanguageJson(key: "job_details")!}
    static var sync_msg : String {return getValueFromLanguageJson(key: "sync_msg")!}
    static var item_add_button : String {return getValueFromLanguageJson(key: "item_add_button")!}
    static var email_button : String {return getValueFromLanguageJson(key: "@email")!}
    static var please_select : String {return getValueFromLanguageJson(key: "please_select")!}
    static var amount : String {return getValueFromLanguageJson(key: "amount")!}
    static var changeLanguage : String {return getValueFromLanguageJson(key: "changeLanguage")!}
    static var document : String {return getValueFromLanguageJson(key: "document")!}
    static var add_tag : String {return getValueFromLanguageJson(key: "add_tag")!}
    static var please_select_country_first : String {return getValueFromLanguageJson(key: "please_select_country_first")!}
    static var clt_updated : String {return getValueFromLanguageJson(key: "clt_updated")!}
    static var discountError : String {return getValueFromLanguageJson(key: "discountError")!}
    static var item_updated : String {return getValueFromLanguageJson(key: "item_updated")!}
    static var please_enter_atleast_one_quantity : String {return getValueFromLanguageJson(key: "please_enter_atleast_one_quantity")!}
    static var mail_success : String {return getServerMsgFromLanguageJson(key: "mail_success")!}
    static var admin_removed_you_from_this_job : String {return getValueFromLanguageJson(key: "admin_removed_you_from_this_job")!}
    static var note_not_available : String {return getValueFromLanguageJson(key: "note_not_available")!}
    static var file_cant_open : String {return getValueFromLanguageJson(key: "file_cant_open")!}
    static var Please_do_not_use_site_name : String {return getValueFromLanguageJson(key: "Please_do_not_use_site_name")!}
    static var clt_added : String {return getValueFromLanguageJson(key: "clt_added")!}    
    static var zip : String {return getValueFromLanguageJson(key: "zip")!}
    static var account_details : String {return getValueFromLanguageJson(key: "account_details")!}
    static var client_details : String {return getValueFromLanguageJson(key: "client_details")!}
    static var add_fieldworker : String {return getValueFromLanguageJson(key: "add_fieldworker")!}
    static var to : String {return getValueFromLanguageJson(key: "to")!}
    static var cc : String {return getValueFromLanguageJson(key: "cc")!}
    static var sort_by : String {return getValueFromLanguageJson(key: "sort_by")!}
    static var date : String {return getValueFromLanguageJson(key: "date")!}
    static var recent : String {return getValueFromLanguageJson(key: "recent")!}
    static var language : String {return getValueFromLanguageJson(key: "language")!}
    static var no_form_added_for_this_job : String {return getValueFromLanguageJson(key: "no_form_added_for_this_job")!}
    static var view_details : String {return getValueFromLanguageJson(key: "view_details")!}
    static var language_success : String {return getValueFromLanguageJson(key: "language_success")!}
    static var frm_updated : String {return getServerMsgFromLanguageJson(key: "frm_updated")!}
    static var select_option : String {return getValueFromLanguageJson(key: "select_option")!}
    static var skip : String {return getValueFromLanguageJson(key: "skip")!}
    static var job_not_sync : String {return getValueFromLanguageJson(key: "job_not_sync")!}
    static var site_not_sync : String {return getValueFromLanguageJson(key: "site_not_sync")!}
    static var enter_file_name : String {return getValueFromLanguageJson(key: "enter_file_name")!}
    static var supplier_cost : String {return getValueFromLanguageJson(key: "supplier_cost")!}
    static var service : String {return getValueFromLanguageJson(key: "service")!}
    static var check_out : String {return getValueFromLanguageJson(key: "check_out")!}
    static var check_in : String {return getValueFromLanguageJson(key: "check_in")!}
    static var services_name : String {return getValueFromLanguageJson(key: "services_name")!}
    static var service_detail : String {return getValueFromLanguageJson(key: "service_detail")!}
    static var service_error : String {return getValueFromLanguageJson(key: "service_error")!}
    static var latitude : String {return getValueFromLanguageJson(key: "latitude")!}
    static var longitued : String {return getValueFromLanguageJson(key: "longitued")!}
    static var quotes : String {return getValueFromLanguageJson(key: "quotes")!}
    static var add_quote : String {return getValueFromLanguageJson(key: "add_quote")!}
    static var quote_desc : String {return getValueFromLanguageJson(key: "quote_desc")!}
    static var quote_instr : String {return getValueFromLanguageJson(key: "quote_instr")!}
    static var quote_po_number : String {return getValueFromLanguageJson(key: "quote_po_number")!}
    static var edit_quote : String {return getValueFromLanguageJson(key: "edit_quote")!}
    static var quotes_start_date : String {return getValueFromLanguageJson(key: "quotes_start_date")!}
    static var quotes_end_date : String {return getValueFromLanguageJson(key: "quotes_end_date")!}
    static var no_quotes_found : String {return getValueFromLanguageJson(key: "no_quotes_found")!}
    static var quote_to_job : String {return getValueFromLanguageJson(key: "quote_to_job")!}
    static var quote_detail : String {return getValueFromLanguageJson(key: "quote_detail")!}
    static var search_quote_code_client_name_address : String {return getValueFromLanguageJson(key: "search_quote_code_client_name_address")!}
    static var quote_status : String {return getValueFromLanguageJson(key: "quote_status")!}
    static var quote_date : String {return getValueFromLanguageJson(key: "quote_date")!}
    static var filter_quotes : String {return getValueFromLanguageJson(key: "filter_quotes")!}
    static var please_select_start_date : String {return getValueFromLanguageJson(key: "please_select_start_date")!}
    static var please_select_end_date : String {return getValueFromLanguageJson(key: "please_select_end_date")!}
    static var start_date : String {return getValueFromLanguageJson(key: "start_date")!}
    static var end_date : String {return getValueFromLanguageJson(key: "end_date")!}
    static var email_quote : String {return getValueFromLanguageJson(key: "email_quote")!}
    static var print_quote : String {return getValueFromLanguageJson(key: "print_quote")!}
    static var create_quote : String {return getValueFromLanguageJson(key: "create_quote")!}
    static var create_job : String {return getValueFromLanguageJson(key: "create_job")!}
    static var create_client : String {return getValueFromLanguageJson(key: "create_client")!}
    static var create_contact : String {return getValueFromLanguageJson(key: "create_contact")!}
    static var create_project : String {return getValueFromLanguageJson(key: "create_project")!}
    static var landmark_addjob : String {return getValueFromLanguageJson(key: "landmark_addjob")!}
    
    
    // For Auditor section
    
    static var remove_item_mandtry : String {return getValueFromLanguageJson(key: "remove_item_mandtry")!}
    static var audit_search_hint : String {return getValueFromLanguageJson(key: "audit_search_hint")!}
    static var audit_nav : String {return getValueFromLanguageJson(key: "audit_nav")!}
    static var detail_audit : String {return getValueFromLanguageJson(key: "detail_audit")!}
    static var detail_equipment : String {return getValueFromLanguageJson(key: "detail_equipment")!}
    static var detail_scan_barcode : String {return getValueFromLanguageJson(key: "detail_scan_barcode")!}
    static var detail_report : String {return getValueFromLanguageJson(key: "detail_report")!}
    static var auditors : String {return getValueFromLanguageJson(key: "auditors")!}
    static var no_auditor_available : String {return getValueFromLanguageJson(key: "no_auditor_available")!}
    static var condition : String {return getValueFromLanguageJson(key: "condition")!}
    static var remark : String {return getValueFromLanguageJson(key: "remark")!}
    static var customer_signature : String {return getValueFromLanguageJson(key: "customer_signature")!}
    static var auditor_signature : String {return getValueFromLanguageJson(key: "auditor_signature")!}
    static var audit_code : String {return getValueFromLanguageJson(key: "audit_code")!}
    static var start : String {return getValueFromLanguageJson(key: "start")!}
    static var end : String {return getValueFromLanguageJson(key: "end")!}
    static var equipment_not_found : String {return getValueFromLanguageJson(key: "equipment_not_found")!}
    static var audit_not_found : String {return getValueFromLanguageJson(key: "audit_not_found")!}
    static var audit_status_change : String {return getValueFromLanguageJson(key: "audit_status_change")!}
    static var scan_barcode_manually : String {return getValueFromLanguageJson(key: "scan_barcode_manually")!}
    static var client_fw_chat : String {return getValueFromLanguageJson(key: "client_fw_chat")!}
    static var datetime : String {return getValueFromLanguageJson(key: "datetime")!}
    static var completion_note : String {return getValueFromLanguageJson(key: "completion_note")!}
    static var doc_des_op : String {return getValueFromLanguageJson(key: "doc_des_op")!}
    static var doc_name : String {return getValueFromLanguageJson(key: "doc_name")!}
    static var sub_up : String {return getValueFromLanguageJson(key: "sub_up")!}
    static var optional : String {return getValueFromLanguageJson(key: "optional")!}
    static var customize : String {return getValueFromLanguageJson(key: "customize")!}
    static var term_condition : String {return getValueFromLanguageJson(key: "term_condition")!}
    static var assign_to_fw : String {return getValueFromLanguageJson(key: "assign_to_fw")!}
    static var side_menu_title_chats : String {return getValueFromLanguageJson(key: "side_menu_title_chats")!}
    static var search_by_username : String {return getValueFromLanguageJson(key: "search_by_username")!}
    static var start_new_chat_here : String {return getValueFromLanguageJson(key: "start_new_chat_here")!}
    static var account_deactivated : String {return getValueFromLanguageJson(key: "account_deactivated")!}
    static var deactivated_msg : String {return getValueFromLanguageJson(key: "deactivated_msg")!}
    static var trying_to_chat : String {return getValueFromLanguageJson(key: "trying_to_chat")!}
    
    //expence
    static var title_expence : String {return getValueFromLanguageJson(key: "title_expence")!}
    static var expense_details : String {return getValueFromLanguageJson(key: "expense_details")!}
    static var expense_history : String {return getValueFromLanguageJson(key: "expense_history")!}
    static var expense_group : String {return getValueFromLanguageJson(key: "expense_group")!}
    static var expense_description : String {return getValueFromLanguageJson(key: "expense_description")!}
    static var add_expense : String {return getValueFromLanguageJson(key: "add_expense")!}
    static var expense_upload : String {return getValueFromLanguageJson(key: "expense_upload")!}
    static var click_here : String {return getValueFromLanguageJson(key: "click_here")!}
    static var expense_nm : String {return getValueFromLanguageJson(key: "expense_nm")!}
    static var expense_date : String {return getValueFromLanguageJson(key: "expense_date")!}
    static var expense_amount : String {return getValueFromLanguageJson(key: "expense_amount")!}
    static var expense_category : String {return getValueFromLanguageJson(key: "expense_category")!}
    static var expense_link : String {return getValueFromLanguageJson(key: "expense_link")!}
    static var expense_none : String {return getValueFromLanguageJson(key: "expense_none")!}
    static var expense_clientid : String {return getValueFromLanguageJson(key: "expense_clientid")!}
    static var claim_reimbu : String {return getValueFromLanguageJson(key: "claim_reimbu")!}
    static var clame_RemberLbl : String {return getValueFromLanguageJson(key: "clame_RemberLbl")!}
    static var expense_jobid : String {return getValueFromLanguageJson(key: "expense_jobid")!}
    static var expense_search_name : String {return getValueFromLanguageJson(key: "expense_search_name")!}
    static var expense_edit : String {return getValueFromLanguageJson(key: "expense_edit")!}
    static var expense_amount_required : String {return getValueFromLanguageJson(key: "expense_amount_required")!}
    static var expense_nm_required : String {return getValueFromLanguageJson(key: "expense_nm_required")!}
    static var expense_added : String {return getValueFromLanguageJson(key: "expense_added")!}
    static var expense_update : String {return getValueFromLanguageJson(key: "expense_update")!}
    static var expense_not_found : String {return getValueFromLanguageJson(key: "expense_not_found")!}
    static var expense_group_detail : String {return getValueFromLanguageJson(key: "expense_group_detail")!}
    static var unschedule_job : String {return getValueFromLanguageJson(key: "unschedule_job")!}
    static var add_appointment : String {return getValueFromLanguageJson(key: "add_appointment")!}
    static var appointment_schedule : String {return getValueFromLanguageJson(key: "appointment_schedule")!}
    static var update_appointment : String {return getValueFromLanguageJson(key: "update_appointment")!}
    static var appointment_edit : String {return getValueFromLanguageJson(key: "appointment_edit")!}
    static var title_appointments : String {return getValueFromLanguageJson(key: "title_appointments")!}
    static var appointment_details : String {return getValueFromLanguageJson(key: "appointment_details")!}
    static var view_on_map : String {return getValueFromLanguageJson(key: "view_on_map")!}
    static var appointment_add_new_attach : String {return getValueFromLanguageJson(key: "appointment_add_new_attach")!}
    static var appointment_not_found : String {return getValueFromLanguageJson(key: "appointment_not_found")!}
    static var appointment : String {return getValueFromLanguageJson(key: "appointment")!}
    static var job : String {return getValueFromLanguageJson(key: "job")!}
    static var appointment_not_sync : String {return getValueFromLanguageJson(key: "appointment_not_sync")!}
    static var link_site : String {return getValueFromLanguageJson(key: "link_site")!}
    static var select_site : String {return getValueFromLanguageJson(key: "select_site")!}
    static var existing : String {return getValueFromLanguageJson(key: "existing")!}
    static var create_new_contact : String {return getValueFromLanguageJson(key: "create_new_contact")!}
    static var appointment_attach_msg : String {return getValueFromLanguageJson(key: "appointment_attach_msg")!}
    static var item_not_sync : String {return getValueFromLanguageJson(key: "item_not_sync")!}
    static var send_email : String {return getValueFromLanguageJson(key: "send_email")!}
    static var email_document : String {return getValueFromLanguageJson(key: "email_document")!}
    static var export_document : String {return getValueFromLanguageJson(key: "export_document")!}
    static var select_all : String {return getValueFromLanguageJson(key: "select_all")!}
    static var select_doc_validation : String {return getValueFromLanguageJson(key: "select_doc_validation")!}
    static var please_contact_admin : String {return getValueFromLanguageJson(key: "please_contact_admin")!}
    static var create_quotation : String {return getValueFromLanguageJson(key: "create_quotation")!}
    static var invoice_can_not_generate_msg : String {return getValueFromLanguageJson(key: "invoice_can_not_generate_msg")!}
    static var reschedule : String {return getValueFromLanguageJson(key: "reschedule")!}
    static var revisit : String {return getValueFromLanguageJson(key: "revisit")!}
    static var require_revisit : String {return getValueFromLanguageJson(key: "require_revisit")!}
    static var revisit_msg_validation : String {return getValueFromLanguageJson(key: "revisit_msg_validation")!}
    static var send_payment_reciept : String {return getValueFromLanguageJson(key: "send_payment_reciept")!}
    static var schedule_date_required : String {return getValueFromLanguageJson(key: "schedule_date_required")!}
    static var close_completed_job_msg : String {return getValueFromLanguageJson(key: "close_completed_job_msg")!}
    static var user_not_found : String {return getValueFromLanguageJson(key: "user_not_found")!}
    static var app_language : String {return getValueFromLanguageJson(key: "app_language")!}
    static var default_view : String {return getValueFromLanguageJson(key: "default_view")!}
    static var start_date_and_time : String {return getValueFromLanguageJson(key: "start_date_and_time")!}
    static var end_date_and_time : String {return getValueFromLanguageJson(key: "end_date_and_time")!}
    static var attachment : String {return getValueFromLanguageJson(key: "document")!}
    static var title_cutom_field : String {return getValueFromLanguageJson(key: "title_cutom_field")!}
    static var doc_here : String {return getValueFromLanguageJson(key: "doc_here")!}
    static var recent_quote : String {return getValueFromLanguageJson(key: "recent_quote")!}
    static var quotation_label : String {return getValueFromLanguageJson(key: "quotation_label")!}
    static var update_remark : String {return getValueFromLanguageJson(key: "update_remark")!}
    static var euipment_remark_update : String {return getValueFromLanguageJson(key: "euipment_remark_update")!}
    static var title_add_equipment : String {return getValueFromLanguageJson(key: "title_add_equipment")!}
    static var equipment : String {return getValueFromLanguageJson(key: "equipment")!}
    static var equipment_model : String {return getValueFromLanguageJson(key: "equipment_model")!}
    static var supplier : String {return getValueFromLanguageJson(key: "supplier")!}
    static var manufacture_date : String {return getValueFromLanguageJson(key: "manufacture_date")!}
    static var equipment_category : String {return getValueFromLanguageJson(key: "equipment_category")!}
    static var equipment_group : String {return getValueFromLanguageJson(key: "equipment_group")!}
    static var brand : String {return getValueFromLanguageJson(key: "brand")!}
    static var serial_no : String {return getValueFromLanguageJson(key: "serial_no")!}
    static var warranty_expiry_date : String {return getValueFromLanguageJson(key: "warranty_expiry_date")!}
    static var purchase_date : String {return getValueFromLanguageJson(key: "purchase_date")!}
    static var type : String {return getValueFromLanguageJson(key: "type")!}
    static var add_images : String {return getValueFromLanguageJson(key: "add_images")!}
    static var serv_prov : String {return getValueFromLanguageJson(key: "serv_prov")!}
    static var gen_bar_code : String {return getValueFromLanguageJson(key: "gen_bar_code")!}
    static var equp_nm_req : String {return getValueFromLanguageJson(key: "equp_nm_req")!}
    static var title_equ_details : String {return getValueFromLanguageJson(key: "title_equ_details")!}
    static var brand_name : String {return getValueFromLanguageJson(key: "brand_name")!}
    static var tariff_rate : String {return getValueFromLanguageJson(key: "tariff_rate")!}
    static var model_no : String {return getValueFromLanguageJson(key: "model_no")!}
    static var go_to_audit : String {return getValueFromLanguageJson(key: "go_to_audit")!}
    static var go_to_job : String {return getValueFromLanguageJson(key: "go_to_job")!}
    static var equipment_serial : String {return getValueFromLanguageJson(key: "equipment_serial")!}
    static var reference : String {return getValueFromLanguageJson(key: "reference")!}
    static var equipment_btn : String {return getValueFromLanguageJson(key: "equipment_btn")!}
    static var remark_added : String {return getValueFromLanguageJson(key: "remark_added")!}
    static var item_qty_update : String {return getValueFromLanguageJson(key: "item_qty_update")!}
    static var owner : String {return getValueFromLanguageJson(key: "owner")!}
    static var add_remark : String {return getValueFromLanguageJson(key: "add_remark")!}
    static var contract : String {return getValueFromLanguageJson(key: "contract")!}
    static var convert_item_to_equ : String {return getValueFromLanguageJson(key: "convert_item_to_equ")!}
    static var recent_job : String {return getValueFromLanguageJson(key: "recent_job")!}
    static var mark_as_done : String {return getValueFromLanguageJson(key: "mark_as_done")!}
    static var title_add_audit : String {return getValueFromLanguageJson(key: "title_add_audit")!}
    static var create_audit : String {return getValueFromLanguageJson(key: "create_audit")!}
    static var audit_desc : String {return getValueFromLanguageJson(key: "audit_desc")!}
    static var audit_instr : String {return getValueFromLanguageJson(key: "audit_instr")!}
    static var add_new_site : String {return getValueFromLanguageJson(key: "add_new_site")!}
    static var audit_not_sync : String {return getValueFromLanguageJson(key: "audit_not_sync")!}
    static var auditors1 : String {return getValueFromLanguageJson(key: "auditors1")!}
    static var capture_barcode : String {return getValueFromLanguageJson(key: "capture_barcode")!}
    // Ricure
    static var attach_image : String {return getValueFromLanguageJson(key: "attach_image")!}
    static var selected_tax_lable : String {return getValueFromLanguageJson(key: "selected_tax_lable")!}
    static var applied_tax : String {return getValueFromLanguageJson(key: "applied_tax")!}
    static var email_job_card : String {return getValueFromLanguageJson(key: "email_job_card")!}
    static var print_job_card : String {return getValueFromLanguageJson(key: "print_job_card")!}
    static var location_permission : String {return getValueFromLanguageJson(key: "location_permission")!}
    static var turn_on : String {return getValueFromLanguageJson(key: "turn_on")!}
    static var location_msg : String {return getValueFromLanguageJson(key: "location_msg")!}
    static var no_thanks : String {return getValueFromLanguageJson(key: "no_thanks")!}
    static var equipment_audit : String {return getValueFromLanguageJson(key: "equipment_audit")!}
    static var equipment_service : String {return getValueFromLanguageJson(key: "equipment_service")!}
    static var upcoming : String {return getValueFromLanguageJson(key: "upcoming")!}
    static var overdue : String {return getValueFromLanguageJson(key: "overdue")!}
    static var work_history : String {return getValueFromLanguageJson(key: "work_history")!}
    static var no_appointment_found : String {return getValueFromLanguageJson(key: "no_appointment_found")!}
    static var site_name_show_permisson : String {return getValueFromLanguageJson(key: "site_name_show_permisson")!}
    static var add_custom_recur : String {return getValueFromLanguageJson(key: "add_custom_recur")!}
    static var custom_recur : String {return getValueFromLanguageJson(key: "custom_recur")!}
    static var custom_recur_msg1 : String {return getValueFromLanguageJson(key: "custom_recur_msg1")!}
    static var starting_on : String {return getValueFromLanguageJson(key: "starting_on")!}
    static var custom_recur_msg2 : String {return getValueFromLanguageJson(key: "custom_recur_msg2")!}
    static var custom_recur_msg3 : String {return getValueFromLanguageJson(key: "custom_recur_msg3")!}
    static var infinity : String {return getValueFromLanguageJson(key: "infinity")!}
    static var add_rucr_for_job : String {return getValueFromLanguageJson(key: "add_rucr_for_job")!}
    static var recuring_pattenr : String {return getValueFromLanguageJson(key: "recuring_pattenr")!}
    static var range_of_recurence : String {return getValueFromLanguageJson(key: "range_of_recurence")!}
    static var radio_everyDay : String {return getValueFromLanguageJson(key: "radio_everyDay")!}
    static var radio_weekDay : String {return getValueFromLanguageJson(key: "radio_weekDay")!}
    static var schel_start : String {return getValueFromLanguageJson(key: "schel_start")!}
    static var radio_no_end_date : String {return getValueFromLanguageJson(key: "radio_no_end_date")!}
    static var radio_end_after : String {return getValueFromLanguageJson(key: "radio_end_after")!}
    static var radio_end_by : String {return getValueFromLanguageJson(key: "radio_end_by")!}
    static var occurance : String {return getValueFromLanguageJson(key: "occurance")!}
    static var day_s : String {return getValueFromLanguageJson(key: "day_s")!}
    static var date_validation : String {return getValueFromLanguageJson(key: "date_validation")!}
    static var select_end_date : String {return getValueFromLanguageJson(key: "select_end_date")!}
    static var dont_create_recur : String {return getValueFromLanguageJson(key: "dont_create_recur")!}
    static var custom_recur_pattern : String {return getValueFromLanguageJson(key: "custom_recur_pattern")!}
    static var never_end : String {return getValueFromLanguageJson(key: "never_end")!}
    static var select_week_days : String {return getValueFromLanguageJson(key: "select_week_days")!}
    static var weekly_msg1 : String {return getValueFromLanguageJson(key: "weekly_msg1")!}
    static var weeks : String {return getValueFromLanguageJson(key: "weeks")!}
    static var every : String {return getValueFromLanguageJson(key: "every")!}
    static var check_mon : String {return getValueFromLanguageJson(key: "check_mon")!}
    static var check_tues : String {return getValueFromLanguageJson(key: "check_tues")!}
    static var check_wedns : String {return getValueFromLanguageJson(key: "check_wedns")!}
    static var check_thurs : String {return getValueFromLanguageJson(key: "check_thurs")!}
    static var check_friday : String {return getValueFromLanguageJson(key: "check_friday")!}
    static var check_satur : String {return getValueFromLanguageJson(key: "check_satur")!}
    static var check_sun : String {return getValueFromLanguageJson(key: "check_sun")!}
    static var first : String {return getValueFromLanguageJson(key: "first")!}
    static var second : String {return getValueFromLanguageJson(key: "second")!}
    static var third : String {return getValueFromLanguageJson(key: "third")!}
    static var forth : String {return getValueFromLanguageJson(key: "forth")!}
    static var last : String {return getValueFromLanguageJson(key: "last")!}
    static var weeks_on : String {return getValueFromLanguageJson(key: "weeks_on")!}
    static var of_every : String {return getValueFromLanguageJson(key: "of_every")!}
    static var months_txt : String {return getValueFromLanguageJson(key: "months_txt")!}
    static var the_radio : String {return getValueFromLanguageJson(key: "the_radio")!}
    static var daily : String {return getValueFromLanguageJson(key: "daily")!}
    static var weekly : String {return getValueFromLanguageJson(key: "weekly")!}
    static var monthly : String {return getValueFromLanguageJson(key: "monthly")!}
    static var months_starting_on : String {return getValueFromLanguageJson(key: "months_starting_on")!}
    static var recuring_job : String {return getValueFromLanguageJson(key: "recuring_job")!}
    static var max_day : String {return getValueFromLanguageJson(key: "max_day")!}
    static var custom : String {return getValueFromLanguageJson(key: "custom")!}
    static var custom_recur_pattern_msg : String {return getValueFromLanguageJson(key: "custom_recur_pattern_msg")!}
    static var normal_recur : String {return getValueFromLanguageJson(key: "normal_recur")!}
    static var job_recur : String {return getValueFromLanguageJson(key: "job_recur")!}
    static var sch_time_required : String {return getValueFromLanguageJson(key: "sch_time_required")!}
    static var stop_recur : String {return getValueFromLanguageJson(key: "stop_recur")!}
    static var delete_recur_msg : String {return getValueFromLanguageJson(key: "delete_recur_msg")!}
    static var do_you_want_save_client : String {return getValueFromLanguageJson(key: "do_you_want_save_client")!}
    static var link_equipment : String {return getValueFromLanguageJson(key: "link_equipment")!}
    static var all : String {return getValueFromLanguageJson(key: "all")!}
    static var linked : String {return getValueFromLanguageJson(key: "linked")!}
    static var unlinked : String {return getValueFromLanguageJson(key: "unlinked")!}
    static var contract_link_msg : String {return getValueFromLanguageJson(key: "contract_link_msg")!}
    static var client_link_msg : String {return getValueFromLanguageJson(key: "client_link_msg")!}
    static var link_client_equipment : String {return getValueFromLanguageJson(key: "link_client_equipment")!}
    static var link_own_equipment : String {return getValueFromLanguageJson(key: "link_own_equipment")!}
    static var expense_Claim_Reimbursement : String {return getValueFromLanguageJson(key: "expense_Claim_Reimbursement")!}
    static var expense_Approved : String {return getValueFromLanguageJson(key: "expense_Approved")!}
    static var expense_Paid : String {return getValueFromLanguageJson(key: "expense_Paid")!}
    static var expense_Open : String {return getValueFromLanguageJson(key: "expense_Open")!}
    static var add_user_mannual : String {return getValueFromLanguageJson(key: "add_user_mannual")!}
    static var view_user_mannual : String {return getValueFromLanguageJson(key: "view_user_mannual")!}
    static var remove_the_image_tag : String {return getValueFromLanguageJson(key: "remove_the_image_tag")!}
    static var after : String {return getValueFromLanguageJson(key: "after")!}
    static var before : String {return getValueFromLanguageJson(key: "before")!}
    static var save_as_completion_notes : String {return getValueFromLanguageJson(key: "save_as_completion_notes")!}
    static var menu_upload_sign : String {return getValueFromLanguageJson(key: "menu_upload_sign")!}
    static var customer_sign_head : String {return getValueFromLanguageJson(key: "customer_sign_head")!}
    static var customer_sign_required : String {return getValueFromLanguageJson(key: "customer_sign_required")!}
    static var sign_uploaded : String {return getValueFromLanguageJson(key: "sign_uploaded")!}
    static var close : String {return getValueFromLanguageJson(key: "close")!}
    static var update_desc_append_complition : String {return getValueFromLanguageJson(key: "update_desc_append_complition")!}
    static var parts : String {return getValueFromLanguageJson(key: "parts")!}
    static var contact_details : String {return getValueFromLanguageJson(key: "contact_details")!}
    static var schedule_details : String {return getValueFromLanguageJson(key: "schedule_details")!}
    static var get_direction : String {return getValueFromLanguageJson(key: "get_direction")!}
    static var item_sync : String {return getValueFromLanguageJson(key: "item_sync")!}
    static var signature_pad : String {return getValueFromLanguageJson(key: "signature_pad")!}
    static var location_not_found : String {return getValueFromLanguageJson(key: "location_not_found")!}
    static var get_current_lat_long : String {return getValueFromLanguageJson(key: "get_current_lat_long")!}
    static var lat_and_lng : String {return getValueFromLanguageJson(key: "lat_and_lng")!}
    static var map_on_view : String {return getValueFromLanguageJson(key: "map_on_view")!}
    static var add_new_audit : String {return getValueFromLanguageJson(key: "add_new_audit")!}
    static var add_audit_offline_msg : String {return getValueFromLanguageJson(key: "add_audit_offline_msg")!}
    static var add_new_auotes : String {return getValueFromLanguageJson(key: "add_new_auotes")!}
    static var add_quotes_offline_msg : String {return getValueFromLanguageJson(key: "add_quotes_offline_msg")!}
    static var add_new_apppinment : String {return getValueFromLanguageJson(key: "add_new_apppinment")!}
    static var add_appoinment_offline_msg : String {return getValueFromLanguageJson(key: "add_appoinment_offline_msg")!}
    static var update_new_quotes : String {return getValueFromLanguageJson(key: "update_new_quotes")!}
    static var update_quotes_offline_msg : String {return getValueFromLanguageJson(key: "update_quotes_offline_msg")!}
    static var update_new_appoinment : String {return getValueFromLanguageJson(key: "update_new_appoinment")!}
    static var job_tags : String {return getValueFromLanguageJson(key: "job_tags")!}
    static var check_in_out_fail : String {return getValueFromLanguageJson(key: "check_in_out_fail")!}
    static var title_timeSheet : String {return getValueFromLanguageJson(key: "title_timeSheet")!}
    static var time_sheet_header : String {return getValueFromLanguageJson(key: "time_sheet_header")!}
    static var time_sheet_sub_header : String {return getValueFromLanguageJson(key: "time_sheet_sub_header")!}
    static var time_sheet_from : String {return getValueFromLanguageJson(key: "time_sheet_from")!}
    static var time_sheet_to : String {return getValueFromLanguageJson(key: "time_sheet_to")!}
    static var time_sheet_date_error : String {return getValueFromLanguageJson(key: "time_sheet_date_error")!}
    static var from_date_error : String {return getValueFromLanguageJson(key: "from_date_error")!}
    static var to_date_error : String {return getValueFromLanguageJson(key: "to_date_error")!}
    static var select_date_range : String {return getValueFromLanguageJson(key: "select_date_range")!}
    static var loca_tax_based : String {return getValueFromLanguageJson(key: "loca_tax_based")!}
    static var loc_tax_msg : String {return getValueFromLanguageJson(key: "loc_tax_msg")!}
    static var select : String {return getValueFromLanguageJson(key: "select")!}
    static var equ_not_found : String {return getValueFromLanguageJson(key: "equ_not_found")!}
    static var title_report : String {return getValueFromLanguageJson(key: "title_report")!}
    static var report_from : String {return getValueFromLanguageJson(key: "report_from")!}
    static var report_to : String {return getValueFromLanguageJson(key: "report_to")!}
    static var download_report : String {return getValueFromLanguageJson(key: "download_report")!}
    static var download_report_lable_stext : String {return getValueFromLanguageJson(key: "download_report_lable_stext")!}
    static var time_report_date_error : String {return getValueFromLanguageJson(key: "time_report_date_error")!}
    static var report_sheet : String {return getValueFromLanguageJson(key: "report_sheet")!}
    static var non_billable : String {return getValueFromLanguageJson(key: "non_billable")!}
    static var billable : String {return getValueFromLanguageJson(key: "billable")!}
    static var text_default : String {return getValueFromLanguageJson(key: "text_default")!}
    static var new_on_hold : String {return getValueFromLanguageJson(key: "new_on_hold")!}
    static var send_client_mail : String {return getValueFromLanguageJson(key: "send_client_mail")!}
    static var quotes_details : String {return getValueFromLanguageJson(key: "quotes_details")!}
    static var quotes_num : String {return getValueFromLanguageJson(key: "quotes_num")!}
    static var add_leave : String {return getValueFromLanguageJson(key: "add_leave")!}
    static var add_notes_leave : String {return getValueFromLanguageJson(key: "add_notes_leave")!}
    static var add_reason_leave : String {return getValueFromLanguageJson(key: "add_reason_leave")!}
    static var leave_date_error : String {return getValueFromLanguageJson(key: "leave_date_error")!}
    static var user_leave : String {return getValueFromLanguageJson(key: "user_leave")!}
    static var all_day_leave : String {return getValueFromLanguageJson(key: "all_day_leave")!}
    static var rate_inclu_tax : String {return getValueFromLanguageJson(key: "rate_inclu_tax")!}
    static var last_serv_date : String {return getValueFromLanguageJson(key: "last_serv_date")!}
    static var barcode_num : String {return getValueFromLanguageJson(key: "barcode_num")!}
    static var are_you_sure_invoice : String {return getValueFromLanguageJson(key: "are_you_sure_invoice")!}
    static var go_to_addjob : String {return getValueFromLanguageJson(key: "go_to_addjob")!}
    static var no_suggesstion : String {return getValueFromLanguageJson(key: "no_suggesstion")!}
    static var add_attachment : String {return getValueFromLanguageJson(key: "add_attachment")!}
    static var scan_insert_barcode : String {return getValueFromLanguageJson(key: "scan_insert_barcode")!}
    static var scan : String {return getValueFromLanguageJson(key: "scan")!}
    static var item_added : String {return getValueFromLanguageJson(key: "item_added")!}
    static var po_number : String {return getValueFromLanguageJson(key: "po_number")!}
    static var static_label_will_remain_same : String {return getValueFromLanguageJson(key: "static_label_will_remain_same")!}
    static var note : String {return getValueFromLanguageJson(key: "note")!}
    static var lead : String {return getValueFromLanguageJson(key: "lead")!}
    static var checkout_time_less_checkin_time : String {return getValueFromLanguageJson(key: "checkout_time_less_checkin_time")!}
    static var checkout_time_greater_current_time : String {return getValueFromLanguageJson(key: "checkout_time_greater_current_time")!}
    static var the_last_checkin : String {return getValueFromLanguageJson(key: "the_last_checkin")!}
    static var do_you_want_to : String {return getValueFromLanguageJson(key: "do_you_want_to")!}
    static var equipment_parts : String {return getValueFromLanguageJson(key: "equipment_parts")!}
    static var parent_equipment : String {return getValueFromLanguageJson(key: "parent_equipment")!}
    static var view_edit_remark : String {return getValueFromLanguageJson(key: "view_edit_remark")!}
    static var item_convrt_count : String {return getValueFromLanguageJson(key: "item_convrt_count")!}
    static var are_you_sure : String {return getValueFromLanguageJson(key: "are_you_sure")!}
    static var job_card : String {return getValueFromLanguageJson(key: "job_card")!}
    static var select_template : String {return getValueFromLanguageJson(key: "select_template")!}
    static var tech_sign : String {return getValueFromLanguageJson(key: "tech_sign")!}
    static var custom_form : String {return getValueFromLanguageJson(key: "custom_form")!}
    static var select_equipment : String {return getValueFromLanguageJson(key: "select_equipment")!}
    static var equipment_items : String {return getValueFromLanguageJson(key: "equipment_items")!}
   
    static var job_equipment_item : String {return getValueFromLanguageJson(key: "job_equipment_item")!}
    static var job_equipment_parts : String {return getValueFromLanguageJson(key: "job_equipment_parts")!}
    static var item_part : String {return getValueFromLanguageJson(key: "item_part")!}
    static var deployed : String {return getValueFromLanguageJson(key: "deployed")!}
    static var replace : String {return getValueFromLanguageJson(key: "replace")!}
    static var do_you_want_to_discard : String {return getValueFromLanguageJson(key: "do_you_want_to_discard")!}
    static var replace_equipment : String {return getValueFromLanguageJson(key: "replace_equipment")!}
    static var items : String {return getValueFromLanguageJson(key: "items")!}
    static var step_1 : String {return getValueFromLanguageJson(key: "step_1")!}
    static var step_2 : String {return getValueFromLanguageJson(key: "step_2")!}
    static var status_sent : String {return getValueFromLanguageJson(key: "status_sent")!}
    static var status_revised : String {return getValueFromLanguageJson(key: "status_revised")!}
    static var service_interval : String {return getValueFromLanguageJson(key: "service_interval")!}
    static var service_due_date : String {return getValueFromLanguageJson(key: "service_due_date")!}
    static var title_replace_equipment : String {return getValueFromLanguageJson(key: "title_replace_equipment")!}
    static var actual_job_time : String {return getValueFromLanguageJson(key: "actual_job_time")!}
    static var actual_start_date_time : String {return getValueFromLanguageJson(key: "actual_start_date_time")!}
    static var actual_end_date_time : String {return getValueFromLanguageJson(key: "actual_end_date_time")!}
    static var travel_start_date_time : String {return getValueFromLanguageJson(key: "travel_start_date_time")!}
    static var travel_end_date_time : String {return getValueFromLanguageJson(key: "travel_end_date_time")!}
    static var completion_details : String {return getValueFromLanguageJson(key: "completion_details")!}
    static var title_add_equipment_part : String {return getValueFromLanguageJson(key: "title_add_equipment_part")!}
    static var status_notes : String {return getValueFromLanguageJson(key: "status_notes")!}
   // static var go_to_addjob : String {return getValueFromLanguageJson(key: "do_you_want_t")!}
    static var do_you_want_t : String {return getValueFromLanguageJson(key: "no_suggesstion")!}
    static var error_actual_start_end : String {return getValueFromLanguageJson(key: "error_actual_start_end")!}
    static var error_travel_start_end : String {return getValueFromLanguageJson(key: "error_travel_start_end")!}
    static var please_select_travel_end_date : String {return getValueFromLanguageJson(key: "please_select_travel_end_date")!}
    static var please_select_travel_start_date : String {return getValueFromLanguageJson(key: "please_select_travel_start_date")!}
    static var please_select_start_end_date : String {return getValueFromLanguageJson(key: "please_select_start_end_date")!}
    static var please_select_start_end_travel_date : String {return getValueFromLanguageJson(key: "please_select_start_end_travel_date")!}
    static var parts_s : String {return getValueFromLanguageJson(key: "parts_s")!}
    static var select_start_actual_date : String {return getValueFromLanguageJson(key: "select_start_actual_date")!}
    static var select_end_actual_date : String {return getValueFromLanguageJson(key: "select_end_actual_date")!}
    static var select_end_travel_date : String {return getValueFromLanguageJson(key: "select_end_travel_date")!}
    static var select_start_travel_date : String {return getValueFromLanguageJson(key: "select_start_travel_date")!}
    static var modifdy : String {return getValueFromLanguageJson(key: "modifdy")!}
    static var modifdy_reavel : String {return getValueFromLanguageJson(key: "modifdy_reavel")!}
    static var select_start_date : String {return getValueFromLanguageJson(key: "select_start_date")!}
    static var select_end_date_new : String {return getValueFromLanguageJson(key: "select_end_date_new")!}
    static var discarded_eq : String {return getValueFromLanguageJson(key: "discarded_eq")!}
    static var time_out_of_scope : String {return getValueFromLanguageJson(key: "time_out_of_scope")!}
    static var clients_eq : String {return getValueFromLanguageJson(key: "clients_eq")!}
    static var my_equipment : String {return getValueFromLanguageJson(key: "my_equipment")!}
    static var service_interval_type : String {return getValueFromLanguageJson(key: "service_interval_type")!}
    static var step_2_note : String {return getValueFromLanguageJson(key: "step_2_note")!}
    static var step_1_note : String {return getValueFromLanguageJson(key: "step_1_note")!}
    static var travel_job_time : String {return getValueFromLanguageJson(key: "travel_job_time")!}
    static var yearly : String {return getValueFromLanguageJson(key: "yearly")!}
    static var equ_as_a_part : String {return getValueFromLanguageJson(key: "equ_as_a_part")!}
    static var equ_status : String {return getValueFromLanguageJson(key: "equ_status")!}
    static var job_card_bold : String {return getValueFromLanguageJson(key: "job_card_bold")!}
    static var extra_feild_1 : String {return getValueFromLanguageJson(key: "extra_feild_1")!}
    static var extra_feild_2 : String {return getValueFromLanguageJson(key: "extra_feild_2")!}
    static var extra_feild_3 : String {return getValueFromLanguageJson(key: "extra_feild_3")!}
    static var extra_feild_4 : String {return getValueFromLanguageJson(key: "extra_feild_4")!}
    static var enble : String {return getValueFromLanguageJson(key: "enble")!}
    static var disble : String {return getValueFromLanguageJson(key: "disble")!}
    static var time_stemp : String {return getValueFromLanguageJson(key: "time_stemp")!}
    static var fetch_des : String {return getValueFromLanguageJson(key: "fetch_des")!}
    static var doc_remove : String {return getValueFromLanguageJson(key: "doc_remove")!}
    static var report_msg : String {return getValueFromLanguageJson(key: "report_msg")!}
    static var dispatch : String {return getValueFromLanguageJson(key: "dispatch")!}
    static var cannot_raise_revisit_request_for_job_which_is_already_marked_as_recurring : String {return getValueFromLanguageJson(key: "cannot_raise_revisit_request_for_job_which_is_already_marked_as_recurring")!}
    static var select_user : String {return getValueFromLanguageJson(key: "select_user")!}
    static var select_leave_type : String {return getValueFromLanguageJson(key: "select_leave_type")!}
    static var wire_transfer : String {return getValueFromLanguageJson(key: "wire_transfer")!}
    static var paypal : String {return getValueFromLanguageJson(key: "paypal")!}
    static var stripe : String {return getValueFromLanguageJson(key: "stripe")!}
    static var Debit_card : String {return getValueFromLanguageJson(key: "Debit_card")!}
    static var day : String {return getValueFromLanguageJson(key: "day")!}
    static var amount_error : String {return getValueFromLanguageJson(key: "amount_error")!}
    static var save_to_draft : String {return getValueFromLanguageJson(key: "save_to_draft")!}
    static var data_Save_On_Draft : String {return getValueFromLanguageJson(key: "data_Save_On_Draft")!}
    static var no_Remark_Add : String {return getValueFromLanguageJson(key: "no_Remark_Add")!}
    static var remarked : String {return getValueFromLanguageJson(key: "remarked")!}
    static var unremarked : String {return getValueFromLanguageJson(key: "unremarked")!}
    static var job_break : String {return getValueFromLanguageJson(key: "job_break")!}
    static var breaks : String {return getValueFromLanguageJson(key: "break")!}
    static var multi_status : String {return getValueFromLanguageJson(key: "multi_status")!}
    static var timezone_Message : String {return getValueFromLanguageJson(key: "timezone_Message")!}
    static var status_required : String {return getValueFromLanguageJson(key: "status_required")!}
    static var ans_added : String {return getValueFromLanguageJson(key: "ans_added")!}
    static var Form_is_already_submitted : String {return getValueFromLanguageJson(key: "Form_is_already_submitted")!}
    static var confirm : String {return getValueFromLanguageJson(key: "confirm")!}
  
}



